### PR TITLE
add dance like none is watching

### PR DESCRIPTION
**Pull request by djh1997**
dance like none is watching encrypt like everyone is wallpaper
can we also look into making a credit card size calendar format like this
* [option 1](http://thumbcalendar.com/)
* [option 2](http://www.armuproducts.com/wallet-cards/PlwalletCalendar2016.jpg)

### CODE REVIEW

**Comment by thieraufc** [comment]
To be grammatically correct, this should read "no one", not "none". In addition, the usage of the modified beats logo may lead to issues regarding the IDGAF licensing-- I'm not sure if it falls into the category of parody. The phrase itself is good, though- as far as I can tell it's in the public domain.

**Comment by jstpcs** [comment]
hi! i like the phrase "dance like nobody’s watching encrypt like everyone is",  @djh1997 can you please open a ticket for this request?  @thieraufc, thanks for your comment, according [this](https://quoteinvestigator.com/2014/02/02/dance/) article and taking in consideration that the original phrase will be modified, i think it's ok to use it.

what concerns the small calendar, i'm not sure that someone still use it, but if so, you are welcome to take any pic from the repo to create one. but anyway thanks again for your proposal.

**Comment by djh1997** [comment]
cool i have changed the wording just wondering about the spacing shall i add the svg(i used inkscape to make) so you can have a play aroung

**Comment by jstpcs** [comment]
@djh1997, i didn't notice that you added a file with wallpaper, i thought it was a request. sorry for confusion. may i take this slogan and create my version of this print? @thieraufc, now i see what you meant by beats logo - you are right, i can't use it.

**Comment by djh1997** [comment]
ahh cool yeah i really like your art style and yeah was never to sure/keen on the beats but i liked the key E

**Comment by jstpcs** [comment]
i opened an [issue](https://github.com/jstpcs/lnxpcs/issues/55) not to forget about it

**Pull request closed without merging**
